# application-dev.yml
server:
  port: 8001

logging:
  pattern:
    console: "%clr(%5p) %clr(-){faint} %clr(%-80.80logger{79}){cyan} %clr(:) %m%n"

spring:
  application:
    name: service-video
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/video_db?serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 180.76.177.246:8848
    sentinel:
      transport:
        dashboard: localhost:8088

mybatis-plus:
  configuration:
    # SQL打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: top/it6666/service_video/mapper/xml/*.xml

feign:
  sentinel:
    enabled: true